# Form implementation generated from reading ui file 'Tools.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 547)
        self.listView = QtWidgets.QListView(parent=Dialog)
        self.listView.setGeometry(QtCore.QRect(30, 210, 701, 311))
        self.listView.setObjectName("listView")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 701, 71))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(270, 10, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 54, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(590, 10, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 50, 54, 16))
        self.label_4.setObjectName("label_4")
        self.D94BLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.D94BLineEdit.setGeometry(QtCore.QRect(150, 50, 181, 20))
        self.D94BLineEdit.setObjectName("D94BLineEdit")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(370, 50, 54, 16))
        self.label_5.setObjectName("label_5")
        self.VersionLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.VersionLineEdit.setGeometry(QtCore.QRect(420, 50, 211, 21))
        self.VersionLineEdit.setObjectName("VersionLineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "ZCUP"))
        self.comboBox.setItemText(1, _translate("Dialog", "ZCUD-M"))
        self.comboBox.setItemText(2, _translate("Dialog", "ZCUD-S"))
        self.label.setText(_translate("Dialog", "Input(A01C)："))
        self.label_2.setText(_translate("Dialog", "Result(A01C)："))
        self.label_3.setText(_translate("Dialog", "Project："))
        self.pushButton.setText(_translate("Dialog", "Analysis"))
        self.label_4.setText(_translate("Dialog", "D94B:"))
        self.label_5.setText(_translate("Dialog", "Version:"))
